name: Cypress tests on push

on:
  push:

jobs:
  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/results
